"""
Deploy — Nginx Config Generator
Automatically rebuilds the Nginx reverse proxy configuration based on running projects in Supabase.
This routes traffic from user subdomains (e.g. app123.deploy.local) to their Docker container ports.
"""
import os
import config
from database import supabase

# In production this would be /etc/nginx/conf.d/deploy.conf
# For local testing, we save it in a local folder
NGINX_CONF_PATH = os.path.join(os.path.dirname(__file__), "nginx", "deploy.conf")
DOMAIN_NAME = "deploy.local" # Change to your actual domain in production (e.g. mypaas.com)

def generate_nginx_config():
    """Fetches all running apps and generates a new Nginx config file."""
    
    print("Fetching active projects from database...")
    res = supabase.table("projects").select("*").eq("status", "RUNNING").execute()
    projects = res.data
    
    # Start the config with a default catch-all block that returns 404
    # if someone visits a subdomain that doesn't exist.
    config_content = f"""
# Auto-generated by Deploy
server {{
    listen 80 default_server;
    server_name _.;
    return 404 "Project not found or not running.";
}}
"""

    for project in projects:
        project_id = project["id"]
        port = project["port"]
        
        # We use the first 8 characters of the ID as the subdomain
        # Example: c6e42784.deploy.local
        subdomain = f"{project_id[:8]}.{DOMAIN_NAME}"
        
        server_block = f"""
server {{
    listen 80;
    server_name {subdomain};

    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support (important for real-time Node.js apps)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }}
}}
"""
        config_content += server_block
        print(f"Mapped {subdomain} -> Port {port}")

    # Ensure the directory exists
    os.makedirs(os.path.dirname(NGINX_CONF_PATH), exist_ok=True)
    
    # Write the new config
    with open(NGINX_CONF_PATH, "w") as f:
        f.write(config_content.strip())
        
    print(f"Successfully generated Nginx config at {NGINX_CONF_PATH}")
    
    # Reload Nginx to apply the new rules
    reload_nginx()

def reload_nginx():
    """Tells Nginx to reload its configuration files without dropping traffic."""
    print("Reloading Nginx...")
    # In production on an EC2 Linux server, this would be:
    # os.system("sudo systemctl reload nginx")
    # For local Windows/Docker testing, we print a message.
    print("[MOCK] os.system('nginx -s reload') executed.")

if __name__ == "__main__":
    generate_nginx_config()
