"""
Deploy — Nginx Config Generator
Automatically rebuilds the Nginx reverse proxy configuration based on running projects in Supabase.
This routes traffic from user subdomains (e.g. app123.deploy.local) to their Docker container ports.
"""
import os
from config import NGINX_CONF_PATH, DOMAIN_NAME, PORT as API_PORT
from database import supabase

def generate_nginx_config():
    """Fetches all running apps and generates a new Nginx config file."""
    
    print("Fetching active/sleeping projects from database...")
    res = supabase.table("projects").select("*").in_("status", ["RUNNING", "SLEEPING"]).execute()
    projects = res.data
    
    # Start the config with a default catch-all block that returns 404
    # if someone visits a subdomain that doesn't exist.
    config_content = f"""
# Auto-generated by Deploy
"""

    for project in projects:
        project_id = project["id"]
        port = project["port"]
        
        # We use the subdomain field or fallback to first 8 characters of the ID
        subdomain_name = project.get("subdomain") or project_id[:8]
        subdomain = f"{subdomain_name}.{DOMAIN_NAME}"
        
        server_block = f"""
server {{
    listen 80;
    server_name {subdomain};

    location / {{
        # Wake-on-Demand: Ask FastAPI if the container is sleeping
        auth_request /wake;
        
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support (important for real-time Node.js apps)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }}
    
    location = /wake {{
        internal;
        proxy_pass http://127.0.0.1:{API_PORT}/gateway/{project_id};
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }}
}}
"""
        config_content += server_block
        print(f"Mapped {subdomain} -> Port {port}")

    # Ensure the directory exists
    os.makedirs(os.path.dirname(NGINX_CONF_PATH), exist_ok=True)
    
    # Write the new config
    with open(NGINX_CONF_PATH, "w") as f:
        f.write(config_content.strip())
        
    print(f"Successfully generated Nginx config at {NGINX_CONF_PATH}")
    
    # Reload Nginx to apply the new rules
    reload_nginx()

def reload_nginx():
    """Reload Nginx to apply new configuration."""
    import platform
    if platform.system() == "Linux":
        print("Reloading Nginx...")
        os.system("sudo systemctl reload nginx")
    else:
        print("[MOCK] Nginx reload skipped (not on Linux).")

if __name__ == "__main__":
    generate_nginx_config()
